name: rpl_studio
description: "RPL Studio - IDE Resmi Rakoda Programming Language"
publish_to: 'none'
version: 5.0.1+501

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: 2.12.0
  ffi: ^2.1.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.5
  path_provider: ^2.1.6
  file_picker: ^11.0.2
  provider: ^6.1.5+1
  flutter_code_editor:
    path: packages/flutter_code_editor
  flutter_highlight: ^0.7.0
  flutter_svg: ^2.0.17
  archive: any
  mobile_scanner: ^7.0.2
  rust_lib_rpl_studio:
    path: rust_builder
  webview_windows: ^0.4.0
  html: ^0.15.6
  window_manager: ^0.5.2
  mysql_client: ^0.0.27
  postgres: ^3.5.12
  sqflite_common_ffi: ^2.4.2
  pluto_grid: ^8.1.0
  uuid: ^4.6.0
  sqlite3_flutter_libs: ^0.6.0+eol
  flutter_riverpod: ^3.3.2
  hugeicons: ^1.1.7
  http: ^1.2.1
  xterm: ^4.0.0
  flutter_pty: ^0.4.0
  desktop_drop: ^0.4.4
  pdfx: any
  excel: ^4.0.6
  csv: any
  flutter_native_splash: 2.3.1
  flutter_inappwebview: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/512.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/512.png"
    background_color: "#1E1E1E"
    theme_color: "#1E1E1E"
  windows:
    generate: true
    image_path: "assets/512.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/512.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
flutter_native_splash:
  color: "#2568E7"
  image: "assets/rakoda-white.png"
  android_12:
    color: "#2568E7"
    image: "assets/rakoda-white-square.png"
    icon_background_color: "#2568E7"
  ios: true
  web: true

